mali: scope L2 clock-slowdown local to the non-devfreq DVFS path
kbase_pm_l2_clock_slow()/kbase_pm_l2_clock_normalize() declare
'struct clk *clk = kbdev->clocks[0]' whenever CONFIG_MALI_MIDGARD_DVFS
is set, but only use it in the '#elif defined(CONFIG_MALI_MIDGARD_DVFS)'
branch, i.e. when CONFIG_MALI_DEVFREQ is NOT set. With both configs
enabled (needed for stock parity: PM_DEVFREQ=y in defconfig, devfreq
governor integration + kbdev->last_frequtil_metrics), the declaration
is dead code and clang -Werror fails the build:

  mali_kbase_pm_backend.c:398:14: error: unused variable 'clk'

Scope the local to 'CONFIG_MALI_MIDGARD_DVFS && !CONFIG_MALI_DEVFREQ'
so it exists exactly when its use branch can compile. No behaviour
change in any configuration.

(cherry picked from commit 9e73f21043383096a386a300c7559620b6dac754)
(cherry picked from commit f97e1f7b06a4037cd781cf416681645f35191fc3)